# Generated by Django 3.2.5 on 2021-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='computerstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
