# Generated by Django 4.2.4 on 2023-09-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="computerstore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product_name", models.CharField(max_length=20)),
                ("Description", models.CharField(max_length=5000)),
                ("image", models.FileField(upload_to="images/")),
            ],
        ),
    ]
